//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enty {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Market {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Market() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("enty.Market", typeof(Market).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:200,&quot;message&quot;:&quot;OK&quot;,&quot;data&quot;:{&quot;playerId&quot;:&quot;Stoffelossi&quot;,&quot;comment&quot;:&quot;Hey&quot;,&quot;inventory&quot;:[{&quot;lastUpdatedAt&quot;:1646911278171,&quot;objectId&quot;:&quot;AV_Head001&quot;,&quot;quantity&quot;:1},{&quot;lastUpdatedAt&quot;:1646911278171,&quot;objectId&quot;:&quot;AV_Head001_01&quot;,&quot;quantity&quot;:1},{&quot;lastUpdatedAt&quot;:1646911278171,&quot;objectId&quot;:&quot;AV_Head001_02&quot;,&quot;quantity&quot;:1},{&quot;lastUpdatedAt&quot;:1646911278171,&quot;objectId&quot;:&quot;AV_Head002&quot;,&quot;quantity&quot;:1},{&quot;lastUpdatedAt&quot;:1646911278171,&quot;objectId&quot;:&quot;AV_Head002_01&quot;,&quot;quantity&quot;:1},{&quot;lastUpdatedAt&quot;:1646911278171,&quot;objectId&quot;:&quot;AV_Head002_02&quot;,&quot;quantity&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Market_json {
            get {
                return ResourceManager.GetString("Market.json", resourceCulture);
            }
        }
    }
}
